name: Deploy Blazor WASM Janken to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3   
      
      # Install .NET Core SDK
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
        
      # Generate the website
      - name: Publish .NET Core Project
        run: dotnet publish BlazorJanken/BlazorJanken.csproj -c Release -o build --nologo

      # changes the base-tag in index.html from '/' to 'blazor-janken' to match GitHub Pages repository subdirectory
      # - name: Change base-tag in index.html from / to blazor-janken
      #   run: sed -i 's/<base href="\/" \/>/<base href="\/blazor-janken\/" \/>/g' build/wwwroot/index.html
        
      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp build/wwwroot/index.html build/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch build/wwwroot/.nojekyll

      # Publish the website
      - name: Commit wwwroot to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on main
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.BLAZOR_JANKEN_PAGES }}
          branch: gh-pages
          folder: build/wwwroot
